version: "3.7"
 
services:
  mongo:
    container_name: streamize-mongo
    image: mongo
    logging:
      driver: "none"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - '27018:27017'
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    logging:
      driver: "none"
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
        - 5673:5672
        - 15673:15672
  redis:
    image: redis:6.2.6-alpine
    logging:
      driver: "none"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    ports:
      - "6380:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamize-api
    restart: on-failure:5 
    volumes:
    #   - ./src:/home/app/src
      - /home/tmp:/home/app/tmp
      - /home/downloads:/home/app/downloads
      - /home/subtitles:/home/app/subtitles
    ports:
      - "8000:3000"
    command: npm start
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
     