version: "3.7"
 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-torrent-downloader
    volumes:
      # - /app/node_modules
      - ./src:/home/app/src
      # - ./:/home/app
      - ./src/tmp:/home/app/src/tmp
    ports:
      - "8000:3000"
    command: npm start
    depends_on:
      - redis
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6380:6379"

