version: "3.7"
 
services:
  mongo:
    container_name: streamize-mongo
    image: mongo
    restart: always
    logging:
      driver: "none"
    networks:
      - nginx-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /data/db
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    restart: always
    logging:
      driver: "none"
    networks:
      - nginx-network
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
  redis:
    image: redis:6.2.6-alpine
    restart: always
    networks:
      - nginx-network
    logging:
      driver: "none"
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamize-api
    networks:
      - nginx-network
    restart: on-failure:5 
    volumes:
      - /home/tmp:/home/app/tmp
      - /home/downloads:/home/app/downloads
      - /home/subtitles:/home/app/subtitles
    command: npm start
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
     

networks:
  nginx-network:
    external: true

