name: Docker image runner

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Rebuild Image and start container
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_USER: ${{ secrets.ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: sudo docker-compose up -d --build
